/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'watchId' : IDL.Text,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Text], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCartItemCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'watchId' : IDL.Text, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Text], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCartItemCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };